package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import finTechAdvisor.BankAccount;
import finTechAdvisor.FinancialMontoring;
import finTechAdvisor.FinanicialGoals;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.text.TextAlignment;
import javafx.stage.Stage;

public class DashboardController implements Initializable{
	@FXML
	private Button back1;
	@FXML
	private Label label1;
	@FXML
	private Label label2;
	@FXML
	private Button next1;
	Main m = new Main();
	
	  @Override
	public void initialize(URL url, ResourceBundle resourceBundle) {
		  		  
	BankAccount curr_account=new BankAccount ("Islamabad","HBL",60000);
    FinancialMontoring obj=new FinancialMontoring(30000,100,110,0,1000,20000,curr_account);
    
    
    obj.montoring(110, 20000, 100, 30000, 1000, curr_account.getBalance());
    
    StringBuilder sb = new StringBuilder();
    sb.append("Balance:").append(curr_account.getBalance()).append("\n");
    sb.append("Investment:").append(obj.investment).append("\n");
    sb.append("Debt:").append(obj.investment).append("\n");
    sb.append("Profit:").append(obj.profit).append("\n");
    sb.append("Taxes:").append(obj.taxes).append("\n");
    sb.append("Saving:").append(obj.saving);
    label1.setText(sb.toString());
    
    String status = obj.strategies(curr_account.getBalance(), obj.saving, obj.debt);
    label2.setText(status);
    label2.setWrapText(true);
    label2.setTextAlignment(TextAlignment.LEFT);
    
			
	    }
	  
	  

	// Event Listener on Button[#back1].onAction
	@FXML
	public void backtouser(ActionEvent event) throws IOException {
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/UserAccount.fxml");
	}
	// Event Listener on Button[#next1].onAction
	@FXML
	public void finalpageOPTION(ActionEvent event) throws IOException {
		// TODO Autogenerated
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/Final.fxml");
	}
	
	//public void 
	
	
}







