package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import finTechAdvisor.FinanicialGoals;
import javafx.event.ActionEvent;

public class EditGoalsController implements Initializable{
    @FXML
    private Button del1;
    @FXML
    private Button back1;
    @FXML
    private ComboBox<FinanicialGoals> combox1; // Inject ComboBox

    public List<FinanicialGoals> receiving = new ArrayList<>();
    Main m = new Main();
    int num;
    String goal;
    Date date;
    String status;
    FinanicialGoals option;
    

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {

    	
        List<FinanicialGoals> log = new ArrayList<>();
		FinanicialGoals obj1 = new FinanicialGoals("Save for vacation", new Date(), "InProgress", 1, "Add");
		FinanicialGoals obj2 = new FinanicialGoals("Buy a new House", new Date(), "InProgress", 2, "Add");

		log.add(obj1);
		log.add(obj2);
		
		
    	combox1.getItems().addAll(log);
    
    }
    


    public void fun(List<FinanicialGoals> data) {
//        receiving = data;
//        System.out.println("Values of receiving:");
//        for (FinanicialGoals goal : receiving) {
//            System.out.println(goal.toString()); // Assuming toString() method of FinanicialGoals is overridden
//        }
//        
//        initializeComboBox(); // Initialize ComboBox when data is received
    }

    // Initialize ComboBox with received data
    private void initializeComboBox() {
        combox1.getItems().addAll(receiving);
    }

    // Event Listener on Button[#del1].onAction
    @FXML
    public void deleteGoal(ActionEvent event) throws IOException {
    	FinanicialGoals main_obj = new FinanicialGoals();
    	main_obj.setFinancialGoals(option.getGoal(), option.getDate(), option.getStatus(), "Delete",option.number);
    	
        // TODO Autogenerated
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/FinancialGoals.fxml");
    }

    // Event Listener on Button[#back1].onAction
    @FXML
    public void BackPage(ActionEvent event) throws IOException {
        // TODO Autogenerated
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/FinancialGoals.fxml");
    }
    
   public void actionlist(ActionEvent event)
    {
	    option= combox1.getValue();
	   
    	
    }
}
