package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class EditGoalsController {
	@FXML
	private Button del1;
	@FXML
	private Button back1;

	// Event Listener on Button[#del1].onAction
	@FXML
	public void deleteGoal(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#back1].onAction
	@FXML
	public void BackPage(ActionEvent event) {
		// TODO Autogenerated
	}
}
