package application;

import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class FinalController {
	@FXML
	private Button backbuton;
	@FXML
	private Button pie;
	@FXML
	private Button profit;
	Main m = new Main();

	// Event Listener on Button[#backbuton].onAction
	@FXML
	public void baccktodashboard(ActionEvent event) throws IOException {
		// TODO Autogenerated
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/dashboard.fxml");
	}
	// Event Listener on Button[#pie].onAction
	@FXML
	public void movetopiechart(ActionEvent event) throws IOException {
		// TODO Autogenerated
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/PIECHART.fxml");
	}
	// Event Listener on Button[#profit].onAction
	@FXML
	public void movetoprofit(ActionEvent event) throws IOException {
		// TODO Autogenerated
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/LINECHART.fxml");
	}
}
