package application;
import finTechAdvisor.*;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import finTechAdvisor.User;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.text.TextAlignment;
import javafx.stage.Stage;

public class FinancialAdviceController  implements Initializable{
	@FXML
	private Button nbtn;
	@FXML
	private Label label1;
    Main m = new Main();

    
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
    	System.out.println("opopo");
        float income = 200;
        int expenses = 100;
        Account ans = new Account("hnaiya", "123");
        BankAccount bankAccount = new BankAccount("haniya", "usman", expenses); 
        Customer obj = new Customer("Haniya", "Islamabad", "03333921920", "hnaiyausman075@gmail.com", "61101-92899234", "username", "password", bankAccount);

        String advice = obj.advise(income, expenses);
        
        if (advice==null)
        {
        	System.out.println("opopo");
        }
        label1.setText(advice);
        label1.setWrapText(true);
        label1.setTextAlignment(TextAlignment.LEFT);
    }

	// Event Listener on Button[#nbtn].onAction
	@FXML
	public void goToHome(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/UserAccount.fxml");
    
	}
}
