package application;

import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class financialadviceformController {
	@FXML
	private Button back1;
	@FXML
	private TextField in1;
	@FXML
	private TextField ex1;
//	private float incomeAmount;
//	private float expensesAmount;
	
    Main m = new Main();

	@FXML
	public void backtomain(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String incomeAmount =in1.getText();
		String expensesAmount = ex1.getText();
		System.out.println("Income "+incomeAmount);
		System.out.println("Expenses "+expensesAmount);
		
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/FinancialAdvice.fxml");
	}

    @FXML
    public void income(ActionEvent event) {
        
       
        
    }

    // Event Listener on TextField[#ex1].onAction
    @FXML
    public void expenses(ActionEvent event) {
        
        
        
    }
}
