package application;

//https://gist.github.com/Da9el00/9c1e63a5ba8c84e0219bb7e59d7a5bad

import javafx.beans.binding.Bindings;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.chart.PieChart;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import finTechAdvisor.BankAccount;
import finTechAdvisor.FinancialMontoring;
import javafx.event.ActionEvent;

public class PIECHARTController implements Initializable{
	@FXML
	private PieChart chart;
	@FXML
	private Button nbtn;
	Main m = new Main();
	
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
    	BankAccount curr_account=new BankAccount ("Islamabad","HBL",60000);
        FinancialMontoring obj=new FinancialMontoring(30000,100,110,0,1000,20000,curr_account);
    	
        ObservableList<PieChart.Data> pieChartData =
        		FXCollections.observableArrayList(
        			    new PieChart.Data("investment",obj.investment),
        			    new PieChart.Data("profit", obj.profit),
        			    new PieChart.Data("taxes", obj.taxes),
        			    new PieChart.Data("saving", obj.saving),
        			    new PieChart.Data("balance",curr_account.getBalance() )
        			);

        
        pieChartData.forEach(data ->
                data.nameProperty().bind(
                        Bindings.concat(
                                data.getName(), " amount: ", data.pieValueProperty()
                        )
                )
        );

        chart.getData().addAll(pieChartData);
    }
	
	
	

	// Event Listener on Button[#nbtn].onAction
	@FXML
	public void goToHome(ActionEvent event) throws IOException {
		// TODO Autogenerated
    	System.out.println("Register Parcel link clicked");
    	Stage s = (Stage) ((Node)event.getSource()).getScene().getWindow();
    	m.changeScene(s, "resources/fxml/Final.fxml");
		
	}
}
